In [1]:
import numpy as np

def blockshaped(arr, nrows, ncols):
    """
    Return an array of shape (n, nrows, ncols) where
    n * nrows * ncols = arr.size

    If arr is a 2D array, the returned array should look like n subblocks with
    each subblock preserving the "physical" layout of arr.
    """
    h, w = arr.shape
    assert h % nrows == 0, "{} rows is not evenly divisble by {}".format(h, nrows)
    assert w % ncols == 0, "{} cols is not evenly divisble by {}".format(w, ncols)
    return (arr.reshape(h//nrows, nrows, -1, ncols)
               .swapaxes(1,2)
               .reshape(-1, nrows, ncols))

In [5]:
c = np.arange(60).reshape((6,10))
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [7]:
A = blockshaped(c,2,2)
print(A.shape)


(15, 2, 2)


In [10]:
image = np.random.rand(5947,13845)

In [17]:
block_size = 500
thresh_valid = 0.3
# padding
pad_row = (image.shape[0]//block_size + 1)*block_size
pad_col = (image.shape[1]//block_size + 1)*block_size
img_pad = np.zeros((pad_row,pad_col))
img_pad[:image.shape[0],:image.shape[1]] = image
print(img_pad.shape)
img_slice_stack = blockshaped(img_pad,block_size,block_size)
print(img_slice_stack.shape)
perc_foreground = np.sum(img_slice_stack.reshape(img_slice_stack.shape[0],-1),axis = -1)/(block_size*block_size)
valid_index = np.where(perc_foreground>thresh_valid)
# save_slices_to_disk(image,valid_index,block_size)
# shift and pad



(6000, 14000)
(336, 500, 500)


(array([  0,   4,  10,  11,  12,  13,  17,  18,  19,  21,  22,  23,  24,
         26,  30,  32,  34,  36,  37,  38,  40,  41,  43,  44,  46,  49,
         50,  53,  54,  56,  58,  59,  60,  61,  62,  67,  68,  69,  70,
         71,  72,  77,  78,  79,  85,  89,  92,  93,  95,  98,  99, 101,
        102, 104, 105, 108, 109, 113, 116, 118, 119, 120, 121, 123, 124,
        129, 132, 133, 134, 137, 138, 141, 142, 150, 152, 155, 156, 159,
        160, 162, 165, 168, 169, 171, 182, 184, 186, 188, 189, 194, 201,
        204, 206, 207, 208, 210, 212, 213, 214, 216, 220, 222, 226, 229,
        231, 232, 234, 237, 238, 240, 241, 245, 247, 248, 249, 250, 255,
        257, 259, 261, 263, 266, 271, 274, 281, 282, 283, 284, 285, 288,
        289, 293, 294, 296, 298, 300, 302, 304, 305, 306]),)

In [21]:
import os
!ls

DensePatch.py  __pycache__  Untitled.ipynb  utils.py


In [29]:
import pandas as pd
DATA = "/mnt/ssd2/AllDatasets/ProstateDataset/Level1"
df = pd.read_csv(DATA+"/train.csv").set_index('image_id')
df.head()

data_provider  isup_grade gleason_score
image_id                                                                
0005f7aaab2800f6170c399693a96917    karolinska           0           0+0
000920ad0b612851f8e01bcc880d9b3d    karolinska           0           0+0
0018ae58b01bdadc8e347995b69f99aa       radboud           4           4+4
001c62abd11fa4b57bf7a6c603a11bb9    karolinska           4           4+4
001d865e65ef5d2579c190a0e0350d8f    karolinska           0           0+0

In [33]:
files = ["000920ad0b612851f8e01bcc880d9b3d","001c62abd11fa4b57bf7a6c603a11bb9"]
df = df.loc[files]
df.head()

data_provider  isup_grade gleason_score
image_id                                                                
000920ad0b612851f8e01bcc880d9b3d    karolinska           0           0+0
001c62abd11fa4b57bf7a6c603a11bb9    karolinska           4           4+4

In [36]:
df.loc["000920ad0b612851f8e01bcc880d9b3d"]["data_provider"]

'karolinska'

In [37]:
df.loc["000920ad0b612851f8e01bcc880d9b3d"]["gleason_score"]

'0+0'

In [38]:
"{:.2f}".format(3.244232)

'3.24'

In [39]:
len(np.array([1,2,3]))

3

In [45]:
np.arange(4)+1

array([1, 2, 3, 4])

In [46]:
import cv2

In [48]:
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [49]:
c.dtype

dtype('int64')

In [51]:
c1 = cv2.resize(c.astype(np.uint8),(4,4))

In [52]:
c1

array([[ 3,  6,  8, 11],
       [18, 21, 23, 26],
       [33, 36, 38, 41],
       [48, 51, 53, 56]], dtype=uint8)